id: P004488
initial_creation_type: ocr
source_metadata:
  id: bdr:W23462
  title: འཕགས་པ་སྤྱན་རས་གཟིགས་ཀྱི་སྒོ་ནས་མིག་གཉིས་སྐྱོན་སེལ་བའི་གདམས་པ་ཟུང་རྔུ་ཚ་གདུང་སེལ་བའི་ཟླ་ཟེར
  author: ''
  volumes: {}
