id: P004488
initial_creation_type: ocr
source_metadata:
  id: bdr:W23462
  title: འཕགས་པ་སྤྱན་རས་གཟིགས་ཀྱི་སྒོ་ནས་མིག་གཉིས་སྐྱོན་སེལ་བའི་གདམས་པ་ཟུང་རྔུ་ཚ་གདུང་སེལ་བའི་ཟླ་ཟེར
  author: ''
  volumes:
    93664f87ac1f4a2685236d0d3740bb00:
      image_group_id: I1PD36261
      title: ''
      volume_number: 1
      total_pages: 10
