id: I4607DA6D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T05:53:45+00:00'
last_modified: '2022-06-08T01:26:26.768536+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23462
  title: འཕགས་པ་སྤྱན་རས་གཟིགས་ཀྱི་སྒོ་ནས་མིག་གཉིས་སྐྱོན་སེལ་བའི་གདམས་པ་ཟུང་རྔུ་ཚ་གདུང་སེལ་བའི་ཟླ་ཟེར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F2F6:
      image_group_id: I1PD36261
      title: ''
      total_pages: 10
      order: 1
      base_file: F2F6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
